import { BodyRegion } from "./types";

export const BODY_REGIONS: BodyRegion[] = [
  {
    id: "head",
    labelVi: "Đầu",
    labelEn: "Head",
    side: "front",
    searchPhrase: "head",
  },
  {
    id: "neck",
    labelVi: "Cổ",
    labelEn: "Neck",
    side: "front",
    searchPhrase: "neck",
  },
  {
    id: "chest",
    labelVi: "Ngực",
    labelEn: "Chest",
    side: "front",
    searchPhrase: "chest",
  },
  {
    id: "abdomen",
    labelVi: "Bụng",
    labelEn: "Abdomen",
    side: "front",
    searchPhrase: "abdomen",
  },
  {
    id: "left_shoulder",
    labelVi: "Vai trái",
    labelEn: "Left shoulder",
    side: "front",
    searchPhrase: "shoulder",
    fallbackSearchPhrases: ["arm"],
  },
  {
    id: "right_shoulder",
    labelVi: "Vai phải",
    labelEn: "Right shoulder",
    side: "front",
    searchPhrase: "shoulder",
    fallbackSearchPhrases: ["arm"],
  },
  {
    id: "left_arm",
    labelVi: "Tay trái",
    labelEn: "Left arm",
    side: "front",
    searchPhrase: "arm",
    fallbackSearchPhrases: ["hand"],
  },
  {
    id: "right_arm",
    labelVi: "Tay phải",
    labelEn: "Right arm",
    side: "front",
    searchPhrase: "arm",
    fallbackSearchPhrases: ["hand"],
  },
  {
    id: "left_hand",
    labelVi: "Bàn tay trái",
    labelEn: "Left hand",
    side: "front",
    searchPhrase: "hand",
  },
  {
    id: "right_hand",
    labelVi: "Bàn tay phải",
    labelEn: "Right hand",
    side: "front",
    searchPhrase: "hand",
  },
  {
    id: "left_leg",
    labelVi: "Chân trái",
    labelEn: "Left leg",
    side: "front",
    searchPhrase: "leg",
  },
  {
    id: "right_leg",
    labelVi: "Chân phải",
    labelEn: "Right leg",
    side: "front",
    searchPhrase: "leg",
  },
  {
    id: "left_knee",
    labelVi: "Đầu gối trái",
    labelEn: "Left knee",
    side: "front",
    searchPhrase: "knee",
    fallbackSearchPhrases: ["leg"],
  },
  {
    id: "right_knee",
    labelVi: "Đầu gối phải",
    labelEn: "Right knee",
    side: "front",
    searchPhrase: "knee",
    fallbackSearchPhrases: ["leg"],
  },
  {
    id: "left_foot",
    labelVi: "Bàn chân trái",
    labelEn: "Left foot",
    side: "front",
    searchPhrase: "foot",
  },
  {
    id: "right_foot",
    labelVi: "Bàn chân phải",
    labelEn: "Right foot",
    side: "front",
    searchPhrase: "foot",
  },
  {
    id: "upper_back",
    labelVi: "Lưng trên",
    labelEn: "Upper back",
    side: "back",
    searchPhrase: "upper back",
    fallbackSearchPhrases: ["back"],
  },
  {
    id: "lower_back",
    labelVi: "Thắt lưng",
    labelEn: "Lower back",
    side: "back",
    searchPhrase: "lower back",
    fallbackSearchPhrases: ["back"],
  },
];